name: Docker Stats Collector

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  collect-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 21.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas
        npm install

    - name: Run stats collector
      run: python scripts/fetch_stats.py

    - name: Convert to JSON
      run: python scripts/convert_to_json.py
    
    - name: Generate img
      run: npm run capture

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git add data/stats.csv docs/data/stats.json docs/img/chart-preview.png
        git commit -m "Update docker stats data" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}